parse_config:
  raw_binding_map:
    "&caps_word": Caps Word

  zmk_keycode_map:
    # custom mappings
    LALT: Opt
    RALT: Opt
    LCTRL: Ctrl
    RCTRL: Ctrl
    LCMD: Cmd
    RCMD: Cmd
    LSHFT: Shift
    RSHFT: Shift
    FSLH:
      tap: "/"
      shifted: "?"
    BSLH:
      tap: '\'
      shifted: "|"

draw_config:
  append_colon_to_layer_header: false
