parse_config:
  mark_alternate_layer_activators: true

  raw_binding_map:
    "&caps_word": Caps Word
    "&mt LS(LA(LC(LCMD))) D":
      tap: D
      shifted: "Hyper"
    "&mt LS(LA(LC(LCMD))) H":
      tap: H
      shifted: "Hyper"

  zmk_keycode_map:
    # Symbols
    GRAVE: "`"
    TILDE: "~"
    EXCL: "!"
    AT: "@"
    HASH: "#"
    DLLR: $
    PRCNT: "%"
    CARET: ^
    AMPS: "&"
    STAR: "*"
    LPAR: (
    RPAR: )
    MINUS: "-"
    UNDER: _
    EQUAL: "="
    PLUS: "+"
    LBKT: "["
    LBRC: "{"
    RBKT: "]"
    RBRC: "}"
    BSLH:
      tap: '\'
      shifted: "|"
    PIPE: "|"
    SEMI:
      tap: ";"
      shifted: ":"
    SQT:
      tap: "'"
      shifted: '"'
    COMMA:
      tap: ","
      shifted: "<"
    DOT:
      tap: "."
      shifted: ">"
    FSLH:
      tap: "/"
      shifted: "?"

    # Navigation
    PG_UP: PgUp
    PG_DN: PgDn

    # Modifiers
    LALT: Opt
    RALT: Opt
    LCTRL: Ctrl
    RCTRL: Ctrl
    LCMD: Cmd
    RCMD: Cmd
    LSHFT: Shift
    RSHFT: Shift

draw_config:
  append_colon_to_layer_header: false
